### ISSUE TITLE
Does Data Type Representation indeed need a Version?

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#108]
Version requires that any id of a Representation is compound, with Code & Version.   Do we intend to version the codes often enough to make the complexity worthwhile?

**Comment by knelson-farmbeltnorth** [comment]
@zwing99 has proposed that we version the entire collection of Representations using semantic versioning.  As such, we would carry a single Representation version number across the entire Application Data Model.   Data consumers would simply reference the appropriate version of the codes.   As such, we could remove the version from each Representatation.   @strhea  and I like the solution.  @aferreyra what are your thoughts?

**Comment by zwing99** [comment]
> @zwing99 has proposed that we version the entire collection of Representations using semantic versioning. As such, we would carry a single Representation version number across the entire Application Data Model. Data consumers would simply reference the appropriate version of the codes. As such, we could remove the version from each Representatation. @strhea and I like the solution. @aferreyra what are your thoughts?

Yes, please version them as one!

**Comment by aferreyra** [comment]
I think it’s fine to version the whole thing. I assume an API implementation will have a ModDate on each entry to facilitate synchronization.

Thanks,

Andres

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by strhea** [comment]
Works for me!
