### ISSUE TITLE
Replacing the ADAPT Raster geodata Model with GeoTiff

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#109]
The Serialization Working Group is examining replacing the abstract model for raster data within the ADAPT standard to external file/URL references to GeoTiff files.

Rasters are currently used in the following places in ADAPT:

Reference Layer.Raster Reference Layer Attributes
Prescription.Spatial Prescription Attributes.Raster Grid Prescription Attributes

**Comment by knelson-farmbeltnorth** [comment]
@strhea @crutt @zwing99 Open question from previous discussion is if we require single band GeoTiffs.  If we go with that approach, we can provide a mapping between references to individual DataTypeRepresentations and separate files.  If we go with multiband, we'll need to define some way of mapping the bands to definitions.   After briefly reading about multiband GeoTiffs, it doesn't appear there is any standard approach to band metadata, and it may be easiest to provide a definition mapping by numeric band index outside of the file.

**Comment by knelson-farmbeltnorth** [comment]
Agreement with @crutt  and @zwing99  in 29 Aug serialization meeting to use the multiband GeoTiff approach above.  Logged Variable definitions will sit external to the GeoTiff, with a mapping to each band index.  We recommend using external GeoTiff files for all Raster data in ADAPT

**Comment by crakerb-ship-it** [comment]
Not 100% sure if this applies, but in a previous AgGateway project related to an imagery standard focused on GeoTIFF. Might be worth aligning or at least looking at if there are relevant parts?

https://aggateway.atlassian.net/wiki/spaces/SG/pages/258670684/AgGateway+Post-Image+Collection+Specification+PICS

**Comment by knelson-farmbeltnorth** [comment]
Agreement in 30 August 2023 meeting to standardize on GeoTiff with mappings to band indices as proposed above.    

@crakerb-ship-it  Reviewing the PICS schema in the above, this appears to target a different problem space and would not be relevant for most raster data (prescriptions) in ADAPT as it stands.   There would be nothing to prevent an implementer from complying with both PICS and the above approach in the same GeoTiff file, however, and we can discuss whether ADAPT standard documentation should refer to this recommendation for imagery that may be placed inside ADAPT.

**Comment by crakerb-ship-it** [comment]
Sounds good, I knew it was much more imagery focused but didn't know for sure if there would be much overlap.
