### ISSUE TITLE
Cleanup & Naming the Application Data Model

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#122]
To help with confusion between the C# ADAPT toolkit and its associated ADM plugin .adm files, I propose we change the root ADAPT container from "Application Data Model" to be "ADAPT Standard Model."

Proprietary Values stands out as one-off at this stage.   Both the keys and the values are free form. I propose we eliminate this object with the understanding that any proprietary data should be alongside and not within the model.

After separating ADAPT from modeling machinery data, we have a set of Device objects that are very shallow:  Device Model, Device Series, Device, and Device Configuration.   With the removal of facilities, Device Configuration serves no purpose other than mapping to a Device.  Device Series and Device Model effectively have a name and parent mapping.   I propose we collapse all 4 into the Device object whereby an Operation maps to a Device, itself containing string properties for Model and Series. 

The OperationGroup (coincident operations completed by connected equipment, the new "LoggedData") is poorly named.  I propose "Equipment Record"

**Comment by zwing99** [comment]
This all seems sane to me. No arguments!

**Comment by knelson-farmbeltnorth** [comment]
Agreement in the 20 September meeting to change "Application Data Model" to "Root," remove Proprietary Values, and change Device Series from a referenceable object to a text field on Device Model, which will map up to Brand (Make).
 
Two items remain open:  Device Configuration and the Operation Group component.

**Comment by knelson-farmbeltnorth** [comment]
@strhea Our current (ADAPT Standard) Device Configuration object is empty.  What setup equipment configuration data would we put in it?

**Comment by strhea** [comment]
I thinking specifically of the offsets necessary to describe a John Deere machine or implement object, but generalized as required.

**Comment by knelson-farmbeltnorth** [comment]
27 September 2023 meeting preliminary conclusions:
1. Reuse Operation between WorkRecord and WorkOrder, replacing Work Item Operation and Prescription.
2. Allow for one to many devices per operation, requiring instead a Logged Variable map to an individual device, following the same pattern as Product.

No discussion in meeting on Device Configuration.

**Comment by knelson-farmbeltnorth** [comment]
@strhea Re Device Configuration, is implement geometry data ever passed in via a setup card in your experience?  The feature of "prescribing" a DDOP exists in ISOXML, I've always found it strange, imagining it was an academic concept that may never have been used.

**Comment by strhea** [comment]
@knelson-farmbeltnorth I just remember needing to clone the existing machine and implement objects (in addition to guidance lines) on a data card before updating the setup data image. I vaguely remember in-line and lateral offset values in addition to some enum that established the reference point (like gps receiver, or hitch).

**Comment by knelson-farmbeltnorth** [comment]
Agreement in 4 Oct 2023 meeting to move Reference Layers inside of Documents and to standardize Operations across Work Orders and Work Records, omitting the intermediate Work Item and Operation Group objects.

Device Configuration is the remaining open topic.

**Comment by knelson-farmbeltnorth** [comment]
Review and ratification of changes at 11 October 2023 meeting
