### ISSUE TITLE
Replace Grower Contact Info with Party Id; Remove Farm Contact Info

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#123]
We currently have no mapping between a party (individual/entity) and a grower.  In addition, we have Contact Info objects on both Grower and Farm.

If the Grower has Contact Info, then we should map that via the Party object so that we can optionally classify the grower as an individual/business entity and allow for entity parents.

I'm not sure why a Farm has Contact Info.   Perhaps a physical address of buildings/yard that will have been associated with the farm when it was a standalone entity?   Without a clear definition, I recommend we remove it.

**Comment by zwing99** [comment]
I am fine with both of these changes. Linking things back to the "Party" 🥳 concept makes total sense to me. I can see the use for contact info on the Farm, but I doubt it is common enough and could easily be handled in other ways in the model (context items?).

**Comment by strhea** [comment]
Our model has contact info at the farm level. It was necessary due to some reporting requirements where certain corporate growers had operations in different states. I request we leave it in.

**Comment by strhea** [comment]
I can make that work, though it may muddy the semantics of the "company" party type.

**Comment by knelson-farmbeltnorth** [comment]
Agreement on 27 September 2023 meeting to remove Contact Info from Grower and Farm and replace it with a link to a Party id
