### ISSUE TITLE
File Naming in ADAPT Serialized Datasets

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#126]
In 1 November 2023 meeting we agreed that 
1. The json "header" file shall be called "adapt.json" (all lower case)
2. Any GeoParquet or GeoTiff files referenced can be named and nested in subdirectories at the users discretion, provided any paths specified are relative to the location of adapt.json
3. We should identify and use standard file extensions for GeoTiff and GeoParquet files.

Open questions for additional discussion:
1. Should we limit allowable file name characters?  
2. What are standard extensions for GeoTiff and GeoParquet?

**Comment by knelson-farmbeltnorth** [comment]
We identified in the prior meeting that ".parquet" is the correct extension for GeoParquet.   By the same logic, it appears ".tiff" is correct for TIFF.  

I would propose we limit filenames to A-Z, a-z, 0-9 and "_".

**Comment by crutt** [comment]
During today's meeting, we discussed using a section similar to the `Avoid Special Characters` section from [NIST Electronic File Organization Tips](https://www.nist.gov/system/files/documents/2022/03/30/ElectronicFileOrganizationTips-2016-03.pdf)

**Comment by knelson-farmbeltnorth** [comment]
Decision in 29 November 2023 meeting to take a file name blacklist rather than whitelist approach and describe characters to avoid as @crutt points out above.

Agreement on ".parquet" and ".tiff" as the proper extensions.
