### ISSUE TITLE
Retiring Data Type Definitions and Codes in Enumerations

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#138]
Currently we have an "IsRetired" boolean on a Data Type Definition.   We do not have the same for an individual item in an enumeration and I believe this is an oversight.

Also, @aferreyra and I discussed how IsRetired may not provide as much detail as we may want.   The Agrisemantics working group in AgGateway has defined the following statuses for a code list or individual code:

_Valid_: The entry is actively being used for new and existing analysis.
_Invalid_: The entry should not be used, because it is in error or otherwise unsuitable for use. It is kept in the infrastructure for forensic / reference purposes.
_Retired_: The entry should not be used to support new data. It was valid in the past, and retained to support historic data. It is not automatically assumed to have been replaced by a new, valid entry.
_Superseded_: The entry should not be used to support new data, because there is a new item that should be used instead. The item in question was valid in the past, and is retained in order to support historic data. It is assumed to have been replaced by a new, valid entry, which it will reference.
_Candidate_: A state allowing a public comment period for new entries that aren't automatically approved, exists in this status for approximately 30 days before either being officially added or removed if issues arise. 

Although Candidate does not fit our processes today, the others all make sense.  In the interests of snapping to work that others in AgGateway are doing, I'm proposing we adopt this, perhaps without Candidate state for now.

Changes proposed:
1. Create a new Enumerated Data Type Definition: "Data Type Definition Status" with the above codes.
2. Change DataTypeDefinition.IsRetired to DataTypeDefinition.StatusCode.
3. Add property DataTypeDefinition.SupersededByCode that will map to another code, to be required when status is "Superseded."
4. Add StatusCode to EnumerationItem so that individual codes can be deprecated.
5. Add EnumerationItem.SupersededByCode.

**Comment by strhea** [comment]
I find this to be reasonable and approve of the proposed changes.

**Comment by knelson-farmbeltnorth** [comment]
Agreement in 17 January 2024 meeting to proceed with these changes. Candidate status will be included with a customized definition for ADAPT
