### ISSUE TITLE
Data vs. Datum

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#16]
I am renaming all singular "Data" objects to "Datum" as in WorkingDatum, OperationDatum, etc. so that we can use OperationData, WorkingData correctly and avoid the use of "Datas". @strhea  Please advise if concerns.

Update, this will just apply to WorkingDatum.   OperationData & LoggedData will be singular with OperationDataCollection & LoggedDataCollection as the plurals.   That would seem most accurate and intuitive.

**Comment by zwing99** [comment]
https://en.wikipedia.org/wiki/Data_(word) - `Any measurement or result is a datum, though data point is now far more common.` 
References to: http://www.bris.ac.uk/Depts/DeafStudiesTeaching/dissert/Writing%20Reports.htm

These are not "be all end all" just ways others have thought about it.

**Comment by knelson-farmbeltnorth** [comment]
That the term "datum" was not known by several people on today's call and connoted a geodetic datum where it was known, I'm convinced use of datum is overly pedantic here.   I like the suggestion of List as it is shorter and equally concise to Collection, but only where it appends to an object with "Data"

Thus WorkingData/WorkingDataList, OperationData/OperationDataList, LoggedData/LoggedDataList vs. Grower/Growers.

**Comment by brycehemme** [comment]
+1 for "List" in the plural/collection use case and "Data" for the singular form

**Comment by knelson-farmbeltnorth** [comment]
These decisions were taken in the 8/10/22 meeting.
