### ISSUE TITLE
CompoundId and ContextItems grouped into common abstract base

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#18]
All entities that have a Compound Id will also have ContextItems.   If one can assign ids, one should be able to assign context items. Exceptions to this were few and appear to have been unintentional.

Items that are included by value requiring context items derive from a different base

**Comment by strhea** [comment]
Agreed. This automatically bakes in extensibility to the identified objects.

**Comment by knelson-farmbeltnorth** [comment]
Agreement on 8/17/22 call.
