### ISSUE TITLE
The accurate name of the component will be used for references and Ids

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#19]
Where an object refers to another, the referred to object shall be appropriately described.

ContextItem.NestedItems -> NestedContextItems
ContextItemEnumItem.Properties -> ContextItems
DeviceElementUse.DeviceConfigurationId ->DeviceElementConfigurationId
DeviceElement.SeriesId -> DeviceSeriesId

UnitOfMeasure.Code -> Unit of Measure Code (for consistency with all foreign key references)

**Comment by strhea** [comment]
Agreed

**Comment by knelson-farmbeltnorth** [comment]
Agreement on 8/17/22 call.
