### ISSUE TITLE
Product Component Changes

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#24]
ProductComponent.IsProduct and Ingredient ID are replaced by ComponentType (Product/Ingredient) and ComponentID (which like IngedientID maps to 2 separate places).    The definitions explain how to use.

**Comment by strhea** [comment]
Agreed

**Comment by knelson-farmbeltnorth** [comment]
In addition, I've collapsed CropNutritionIngredient, ActiveIngredient and InertIngredient into a single Ingredient entity that has comprehensive functionality.

**Comment by knelson-farmbeltnorth** [comment]
24 August committee agreement on Product Component changes.   Ingredient should be a polymorphic entity separating crop nutrition ingredients from chemical ingredients
