### ISSUE TITLE
DeviceElement.Parent Id

### ISSUE THREAD

**Issue by kelly-nelson** [ADAPT/Standard#31]
I've changed DeviceElement.DeviceParentId to ParentId with an explanation as to the conditionality of the type of parent (Device Model/Device Element)

**Comment by knelson-farmbeltnorth** [comment]
Correction:   DeviceElement.ParentId refers only to parents of the same type (DeviceElement).   An empty parent signifies the root of a hierarchy.   Per 8/17/22 meeting discussion, Device Model Id is now optional, following the pattern of Series, Manufacturer, etc.   A DeviceElement need not refer to a Model.

**Comment by knelson-farmbeltnorth** [comment]
Superseded by #76
