### ISSUE TITLE
Ingredient Use is an orphaned, undefined entity

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#35]

**Comment by knelson-farmbeltnorth** [comment]
My inclination is to remove it as an incomplete concept.   Per #24 I'm not sure it is necessary.

**Comment by strhea** [comment]
Seems like this is covered in ProductComponent from the perspective of describing the IDENTITY of a product. Describing the USE of a product resource is handled by ProduceUse.

**Comment by knelson-farmbeltnorth** [comment]
24 August committee agreement to remove this entity
