### ISSUE TITLE
Clarifying (Spatial) Point

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#40]
Use of WGS84 coordinates is implied throughout ADAPT.   Point simply has doubles that define X and Y, and there is universal usage that these mean WGS84 Longitude and Latitude, respectively.     

While we may wish to abbreviate these X & Y during serialization, we should probably rename them Longitude and Latitude.

Point.Z needs definition.   Meters above sea level (+) or below sea level (-) would seem to be the widest interpretation, and it ought to be renamed Elevation.

**Comment by strhea** [comment]
Agreed

**Comment by knelson-farmbeltnorth** [comment]
Discussed at 8/17/22 meeting.  We will standardize on WGS84 and change the properties to Lattude, longitude and elevation
