### ISSUE TITLE
Bounding Box Definition

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#41]
Bounding Box MinX, MinY, MaxX and MaxY are currently defined as NumericRepresentationValues.    If Point coordinates are always WGS84 and represented as doubles, then BoundingBox should have 4 doubles instead of 4 NRVs and potentially be defined as MinLatitude, MaxLatitude, MinLongitude, MaxLongitude.

**Comment by aferreyra** [comment]
Your reasoning is sound. Did anyone in recent memory express a need to represent data in UTM (or Gauss-Kruger, etc.) for any reason? That's the only scenario that would justify a NRV.

**Comment by knelson-farmbeltnorth** [comment]
@aferreyra As geojson does, I think we need to define that any geospatial data in ADAPT is necessarily in EPSG 4326.    We discussed this as an unwritten rule in years past.    If someone needs to reproject in UTM then they can use the GIS tooling of their choice to do so.   Otherwise we are trying to be too many things at once.  See my excursus on #44

**Comment by strhea** [comment]
Agreed.

**Comment by knelson-farmbeltnorth** [comment]
Discussed at 8/17/22 meeting.   We will rename to MinLongitude, etc.

**Comment by knelson-farmbeltnorth** [comment]
Superseded by #109.  There is no longer a Bounding Box entity in the ADAPT Standard.
