### ISSUE TITLE
Document Correlation

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#46]
@strhea DocumentCorrelation is currently the only entity that requires the 5 document types (Observations, Work Order, Work Record, Plan and Recommendation) be treated polymorphically due to its DocumentId property.   We need to address these 5 entities first (see #37), but assuming we retain some or all of them, I'd like to avoid the polymorphism here.   Having a Document, with WorkOrderAttributes doesn't flow as neatly as a Product with CropVarietyAttributes.

Also, I recognize that there was theory behind this object, but I think we need to revisit the what and why.   The three variations (casual, contextual, compositional) leave a lot of room for interpretation.    Also, that the correlation is external to the document seems problematic.   If we want to track relationships, then why not do so on the objects themselves?

If we keep this object, we need to clarify DocumentId vs. OriginatingDocumentId.  Conceivably the latter is the "prior" document that governs the meaning of the document relationship?   I.e., in a compositional correlation, is the OriginatingDocument the one that contains the "Document."     Here again modeling the relationships on the objects initially strikes me as cleaner.

**Comment by knelson-farmbeltnorth** [comment]
The more I look at the documents entities, the more I feel that this concept belongs inside the documents themselves.  Unless I am missing nuance in DocumentCorrelation, I believe we could achieve all the functionality by simply adding two optional properties to the base document:   OriginatingDocumentID and OriginatingDocumentRelationshipType. 

@strhea @aferreyra Please advise.

**Comment by strhea** [comment]
While I would prefer to have a separate metadata system for asserting relationships between documents (or other pieces of data), I acknowledge that we don't have that right now. In the interest of simplicity I'm fine with adding an array of objects to express those relationships to the document.

**Comment by knelson-farmbeltnorth** [comment]
Agreement in October 12, 2022 meeting to embed correlation information within the documents.   Each document will have a collection of Document Correlations
