### ISSUE TITLE
FieldBoundary.OriginalEpsgCode

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#47]
I've defined this property as "Any coordinate system other than 4326 that the boundary may have been represented in prior to its conversion to 4326."

What is unclear is why we have it.   What does this information enable?

**Comment by brycehemme** [comment]
I can't come up with a solid purpose for this but it might be useful if lossy or imprecise reprojections occur from the source coordinate system to 4326.

**Comment by knelson-farmbeltnorth** [comment]
Per 8/17/22 meeting, we will delete OriginalEPSGCode from GuidancePattern & FieldBoundary.  It is not actionable information.
