### ISSUE TITLE
Context Items

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#52]
There are a few open questions about Context Items:

1. In the current C# Value is listed as Optional, I've tentatively marked this required in Score.  What use is a Context Item without a Value?

2. We may need to formalize ContextItem usage more than it is currently.  When used, many implementers have simply created their own Key/Value pairs
    a. Is ContextItem.org to be the governing vocabulary for Context Items?  If so, how does one engage with that group and add entities?   We need to clarify this question in the model. 
    b. If there is a governing vocabulary, is is mandatory that any custom keys be prefixed with "pr" to represent proprietary codes.   This is neither enforced nor common practice today.  

3. Does ContextItemDefinition belong inside the model or is it an associated data model such as the UnitSystem or RepresentationSystem?   Today there is no way to persist this entity inside the model.    Per discussion with @strhea, it sounds like this object may instead belong in a ContextItem system model vs. in the ADAPT model itself.

**Comment by knelson-farmbeltnorth** [comment]
Re #3, per discussion with @strhea, the intent of ContextItemDefinition within the model allows ad hoc ContextItems to carry a definition.   ContextItems defined and documented externally do not need the internal definition.

**Comment by strhea** [comment]
Re #1: In an instance where you are assembling a ContextItem instance that encapsulates multiple, related ContextItems (with their values) in the NestedItems property, the "container" ContextItem would NOT have a Value so it needs to remain optional. The usual example of this is the Public Land Survey System (PLSS) information that would be represented as a nested context item.

Re #2a: Yes, the context item service should house the formal vocabulary and should be administered through WG00 - Agrisemantics. There is an existing submission process currently mediated with an Excel template, but probably needs to be refactored into a digital form submission system.

Re #2b: Some prefix should be used to designate ad-hoc or proprietary context items. I can't say I like the "pr" that has been used in the past.

Re #3. Reality tends to be more chaotic, so in my opinion it would be unreasonable to try and restrict the use of the context item system. As a result, it's necessary to allow the ad-hoc definition of ContextItemDefinitions that could be sent along with the data using non-standard/unregistered ContextItems.

**Comment by strhea** [comment]
For now, yes - contextitem.org is the source of truth.
