### ISSUE TITLE
Reference Layers RasterData object:  Defining Raster Values

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#57]
As modeled today in the C#, the Raster Reference Layer contains 3 collections of a RasterData object that contains a 2-dimensional array based on type: enumerated, numeric or string.     2-dimensional arrays are language constructs that do not translate well to our logical model.

In my experience, raster values are often defined from the lower left cell laterally in a single-dimension array/collection.  I.e., if a raster is 20 columns by 10 rows the first value (0,0) defines the left cell/pixel of the bottom row.     The values list continues in order through (0,19) at which time it moves to (1,0) and repeats until the final (200th) value at (9,19), the top right.

My suggestion is that we adopt this one-dimensional convention for flexibility in modeling in places where multi-dimensional arrays are not supported.   This is the pattern already used by the RasterGridPrescription entity, and follows the convention in ISO11783.

**Comment by brycehemme** [comment]
Do we think there's an actual need to model our own raster construct or should the model simply reference a raster document in a well-defined raster format such as GeoTIFF? This starts to bleed into the serialization topic but you also run the risk of creating a property that is large and inefficient. I'm not opposed to it being defined as an array but also want us to avoid adding unnecessary complexity where there's already well-understood and widely adopted standards.

**Comment by strhea** [comment]
No objection to switching to a single-dimension array. @brycehemme makes an excellent point about perhaps letting this object reference an external artifact (like a GeoTIFF). I think the same argument can be made for the SpatialReferenceLayer class and the high-density spatial data as well.

**Comment by knelson-farmbeltnorth** [comment]
Agreement in Oct 5 2022 meeting use the same ordered collection of values laid out in my first comment in order to be consistent with the RasterGridPrescription entity.

**Comment by knelson-farmbeltnorth** [comment]
Superseded by #109
