### ISSUE TITLE
Is PersonRole really just Role?

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#6]
Can a role be assumed by a company, grower, etc.?  Today we just have the concept of Role relating to a Person.

**Comment by strhea** [comment]
It would make sense for a role to be assumed by either a company or a person. In the case of describing an Applicator/Operator in relation to a field operation, I can see how that role might be filled by a service provider - in which case the grower may or may not have information about the specific person.

**Comment by knelson-farmbeltnorth** [comment]
Discussed in the Aug 10 call -> Role is applicable more widely.   Closing this item for inclusion within the larger scope of #7
