### ISSUE TITLE
UnitOfMeasure should not be an object within the model

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#61]
Discussion on 24 August committee meeting:  Since we require the ADAPT unit of measure system, should we have anything more than Unit of Measure code on any object in the model?

**Comment by strhea** [comment]
Agreed.

**Comment by zwing99** [comment]
Agreed.

**Comment by knelson-farmbeltnorth** [comment]
Confirmed at September 7, 2022 meeting

**Comment by knelson-farmbeltnorth** [comment]
Unit of Measure and UnitOfMeasure Dimension are replaced by the respective codes from the ADAPT Unit System.
