### ISSUE TITLE
Separation of Crop Season & Timing Event from Time Scope

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#65]
The Sept 7 2022 meeting resolved to separate the concepts of Crop Season and Timing Event (referenceable, stand alone events) from Time Scopes (simple start/end values).

The new objects are 
Crop Season 
 -Id
 -ContextItems
 -Start (opt)
 -End (opt)
Definition:  The span of time for which field operations contribute to a particular growing season.   For many areas, this is approximately a year in length.  E.g., In the northern hemisphere, Crop Season "2022" may extend from the first operations following harvest in the fall of 2021 to the last harvest activities in the fall of 2022.

Timing Event
 -Id
 -ContextItems
 -Start (opt)
 -End (opt)
 -Crop Season Id (opt)
Definition:  An referenceable event defined by its interval.   E.g., "2022 Harvest" or "2022 Pre-Emergence"

Of items today referencing Time Scopes, go forward behavior is currently defined as follows.

1. Time Scopes only.    These items define their own start and end.   Any relation to seasons or events is appropriate on parent/related objects if at all.
  -Guidance Shift
  -Load
  -Summary
  -LoggedData
  -DocumentCorrelation
  -Obs
  -ObsCollection
  -DeviceElementConfiguration
  -CalibrationFactor
  -IrrigationItem 
  -PersonRole
  -GuidanceAllocation
  -IrrigationRecord
  -IrrigationRecord

2. TimeScopes, CropSeasons and/or Timing Events.   Any of the concepts can pertain to these.
  -ObsDataset   (multiple, optional)
  -Document (base)   (multiple, optional)
  -ContextItem   (multiple, optional)
  -Note   (multiple, optional)
  -Prescription  (multiple, optional)
  -WorkItem  (multiple, optional)

3. Crop Season only.   Only season pertains. 
  -FieldBoundary (multiple, optional)
  -CropZone (single, required)

4. Per discussion in the Sept 7 meeting, Time Scopes are removed from Farm and Field and similarly will omit the other concepts.   Crop Zone should be used for any organizational hierarchies with defined seasons.

@aferreyra From my reading of comments on ObsCollection and IrrigationCollection I understood these to be more narrowly defined than a season, and that the season belonged on the ObsDataset (didn't find an analog for Irrigation).     Please advise if the objects have a different intent.
@strhea @zwing99 Please double check my work.   It was done in the spirit that while one might decide to tag a season anywhere, that runs afoul of guiding implementers into a deterministic pattern that consumers can anticipate.

**Comment by strhea** [comment]
1. Should CropSeason have an explicit crop reference as part of it's structure?
2. Let's just drop TimingEvent and reimplement it as a ContextItem.
3. How do you communicate historical G/F/F tree structures without having CropSeason at the Farm & Field level?

**Comment by knelson-farmbeltnorth** [comment]
@strhea Re your feedback:
1. CropSeason doesn't reference a Crop.   I'll rename it GrowingSeason for clarity
2. I'm all for that.  
3. So long as we have a crop zone, that is the place to associate time information.   If there is a use case requiring rendering of the active GFF tree as of a specific date, then it should be defined as those entities linked to active data.

**Comment by knelson-farmbeltnorth** [comment]
Agreement in Sept 21, 2022 meeting that time scopes should be omitted from GFF and that TimingEvent is indeed not needed.
