### ISSUE TITLE
Defined Properties within the model should be typed as NumericValue/EnumerationMember vs. NumericRepresentationValue/EnumerationValue

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#67]
There are numerous numeric properties throughout the model that are typed as NumericRepresentationValues and a few (many more after we migrate all enumerations) as EnumeratedValues.    These should not allow the definition of a Representation. 

In the case of the numeric items on defined properties, the choice of representation is irrelevant.   E.g., Swath Width, Quantity, Density.   We simply require a value and a unit of measure (NumericValue).   The property itself tells us what it is.   

In the case of enumerated items on defined properties, only a single enumeration is allowable.   We cannot allow implementers to vary the definition of the enumeration, there must be the expectation that a property maps to a specific enumerated representation.   In most cases, this mirrors what is already enforced by the strongly typed enumerations in C#.   These should be an EnumerationMember (the code/value)

I've remapped all affected types in Score.

**Comment by strhea** [comment]
Agreed.

**Comment by knelson-farmbeltnorth** [comment]
Accepted in Sept 28, 2022 meeting
