### ISSUE TITLE
Reconciling GpsSourceTypeEnum with dtSignalType

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#69]
In moving the C# enums into the Representation System, there is a clash with the dtSignalType enumeration.    GPSSourceType is used on several objects and dtSignalType is used on SpatialRecord.   The contain similar values but translating one to the other is not immediately clear.

Since GPSSourceEnum appears to be comprehensive to Deere's types (from dtSignalType) as well as ISO11783-10's vocabulary, the simplest solution may be to retire dtSignalType and replace it with dtGpsSourceType.

**Comment by strhea** [comment]
Agreed

**Comment by crutt** [comment]
I’m also in agreement

**Comment by knelson-farmbeltnorth** [comment]
Agreement in Oct 5 2022 meeting
