### ISSUE TITLE
Remove Implementation Alternatives with Documents Entities by Enforcing the Base Document Types

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#70]
We've already made a decision as a group on #38 that we will not have duplicate ID collections on higher level items.  E.g., we won't have both a required FieldID on a WorkItem, and then a list of FieldIDs on a Workorder.   The WorkOrder's FieldIDs are by necessity the aggregation of its children's data.   Indexing the IDs in the data is a separate concern from defining a cohesive data standard.  Conceivably any code implementation of the model could include some sort of indexing facility for rapidly navigating the tree to an ID.     Following this concept, I believe we need to undo the hierarchical options and shortcuts in the ADM/Documents class so that everything follows a defined hierarchy.

Today one may optionally create WorkRecords, WorkOrders, etc. that contain LoggedData, Summaries, WorkItems, or instead simply promote the latter to top-level entities within ADM/Documents, skipping the containing documents (https://github.com/ADAPT/ADAPT/blob/develop/source/ADAPT/ADM/Documents.cs).   This was perhaps done in part to achieve easy access to the lower level entities via ID, and perhaps because the base documents were not seen to be universally relevant.  The more alternatives for the model creator, the more confusion for the model consumer.

I'm currently thinking we make one of the base document types required in all cases.   These types are currently Plan, Recommendation, WorkOrder, WorkRecord, and Observations.    As such, ADM/Documents would simply have these 5 top level collections, and there would be no possibility for differing interpretations of the document hierarchy.    If you simply wish to model a single collection of prescriptions or a single collection of LoggedData, you have one Recommendation/WorkOrder called "2023 Prescriptions" and one WorkRecord called "2022 Harvest Data."   Implementers that wish to provide more specific and numerous documents can do so easily within the same model.    

This change would involve removing all but the base types from the Documents container entity, and changing the base types to include their children by value vs. by reference.

This may lead to some discussion on whether our current 5 base types are correct and comprehensive, but I'd like to treat this as secondary to the design question of enforcing consistency in the hierarchical modeling.

@aferreyra @strhea @crutt @andrew-granular I'd like to discuss at next week's meeting.   Let me know of any feedback in the meantime.

**Comment by strhea** [comment]
With the exception of Plan (which is a season-long strategic document), I think each document (Recommendation, Work Order, Work Record) needs to represent the planned or actual execution of a set of coincident operations on a field/cropzone.

**Comment by knelson-farmbeltnorth** [comment]
Changes agreed in October 12, 2022.  Per @strhea 's comment above, I've moved Field Id, Crop Zone Id and Season Id from all lower level document objects to the base document class.  As such, any document is scoped to an individual field/crop zone.

**Comment by knelson-farmbeltnorth** [comment]
We revisited this decision in detailed discussions with @strhea  and @aferreyra  on October 17, 2022.  We determined that WorkOrder and WorkRecord are necessarily scoped to a single field, Plan and Recommendation are scoped to a single crop (except in cases of intercropping) and may or may not specify fields, while Observations Document follows its own pattern with a Feature of Interest Code Component.

**Comment by knelson-farmbeltnorth** [comment]
Recent changes agreed in Oct 26, 2022 meeting
