### ISSUE TITLE
Machine-Centric Objects to Remove

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#76]
Proposal #74 led to a re-examination of the role of ADAPT in reporting machinery-specific data.   At a high level, the team has agreed to step away from wrapping ISO11783-10 functionality (data from the point of view of the machinery) inside ADAPT.   Instead, machinery data within ADAPT should be limited to identifying separate high level machines and limited configuration data (see #77).

As a result, the following components within ADAPT are candidates for removal:

_Device Objects_
Device Model
Device Element
Device Series
Device Element Use (data variables are listed on the Asset Configuration, totals on the Field Operation)
Device Element Configuration 
Machine Configuration
Implement Configuration
Section Configuration
GPS Receiver Offsets
Reference Point Offsets

_Equipment Connection Data_
Hitch Point
Connection
Equipment Configuration
Equipment Configuration Group (connected Assets are grouped by Work Record Data)

_Prescription Data_
Data Log Triggers (any implementation would move to ISOv4Plugin)

_Guidance Data_
All

_Irrigation Configuration Data_ 
Endgun Configuration
Endgun Table 
Endgun Table Entry
IrrSectionConfiguration
IrrSystemConfiguration
 (We intend to integrate Irrigation into Field Operations in a future release)

**Comment by knelson-farmbeltnorth** [comment]
Initial discussion in 11 Jan 2023 meeting.   Several objections to removing guidance since this is data that some FMIS systems are maintaining today.

**Comment by strhea** [comment]
I agree with keeping the guidance information as we have it now.

As for the others: 
    I suspect there is value in keeping the "device" Model and Series to help in defining the identity of the "device", in the same way we use Manufacturer and Brand.
    We will need some kind of simplified configuration object for the "device" that would allow us to express things like a fixed GPS location, association with a Field, or association with other "devices".

**Comment by knelson-farmbeltnorth** [comment]
Agreement in 1 Feb 2023 meeting to remove all above except Guidance, Device Model & Device Series.
