### ISSUE TITLE
Revisiting Product Classifications

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#83]
Products in ADAPT currently carry several classifications:  Form, Type, Category and Status.

Form is Gas, Liquid, Solid, Unknown

Status is Active, Inactive, Retired, No Longer Sold

Type is Chemical, Fertilizer, Generic, Mix, Variety

Category is Additive, Carrier, Fungicide, GrowthRegulator, Insecticide, Herbicide, Manure, Nitrogen Stabilizer, Unknown, Variety, Fertilizer (non-manure), Pesticide (non-insecticide)

-

Re Status, do the 3 non-active values have enough semantic distinction that we can assume they will be consistently set?

Re Category vs. Type, 
-is this two-tier layering useful?  We have reiterated Unknown, Variety, and Fertilizer at the end of Category since ostensibly it doesn't apply to those.    However, if I were to classify a manure product, I'd use Type = Fertilizer, Category = Manure
-does "Chemical" carry the right meaning here?  What about chemical vs. organic fertilizers?
-does "Mix" belong as a sibling of the others?
-since we have Herbicides, Insecticides and Fungicides, can we not fill out the other known types of pesticides in agriculture vs. including the generic term and inviting misclassification?

**Comment by knelson-farmbeltnorth** [comment]
After researching further, I'm proposing the following:

Status should be either Active or Inactive.    AGIIS uses these 2 options that can be defined simply as either available in the market or not.   

Type and Category should be consolidated into a single list to avoid malformed data (e.g., Type=Variety, Category=Nitrogen Stabilizer).    I suggest we keep the term Type and propose the following list for discussion:

- Not Specified
- Seed - Undeveloped plant embryos
- Plant - Any stage of a plants other than seed used to initiate cultivation
- Fertilizer - A crop nutrition product
- Herbicide - A weed control product
- Insecticide - An insect control product
- Fungicide - A fungus control product
- Rodenticide - A rodent control product
- Spray Adjuvant - Any substance added to a liquid spray product to enhance its performance
- Nitrogen Stabilizer - A product to limit soil nitrogen loss 
- Growth Regulator - Non-nutrient chemicals that modify plant growth
- Feed - An animal nutrition product
- Water - Used for plant irrigation, animal hydration or as a spray carrier

Not Specified would serve to handle any unknown/generic/other cases.

I omitted Mix since any product can be configured as a mix.   The Product model in ADAPT supports ingredients for all types of product.

I omitted Carrier since all carriers other than Water fit into another category.

**Comment by knelson-farmbeltnorth** [comment]
Also for discussion here is that there is not currently a type for harvested commodity.  We do have a child class of product for this concept (including a crop id), but it is not otherwise referenced in the model.  Some plugins may currently output models where harvest operations map to a harvested commodity product.

**Comment by knelson-farmbeltnorth** [comment]
I missed Defoliant in the above list.   I don't believe that fits into any of the other types.

**Comment by crutt** [comment]
A `defoliant` could potentially be classified as a `herbicide`, however I think the actual agricultural use case is often as a pre-harvest application. If that's accurate, categorizing it separately is a useful distinction.

**Comment by knelson-farmbeltnorth** [comment]
Agreement in 19 July 2023 meeting to adopt the above list with the addition of Mix, Harvested Commodity, Nematicide, Defoliant, and separating Chemical Fertilizer from Manure.   Also agreement to simplify Product Status as stated above.
