### ISSUE TITLE
Data Type Definition:  Central Object

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#88]
The Data Type Definition (see #87) intends to replace both Representation and ContextItemDefinition in the ADAPT Standard.   It has the following concepts:

1. Identifier Code.   This is the key by which any usage would refer to the definition.  See #89 
2. Version.  Following the [Context Item paper,](https://aggateway.atlassian.net/wiki/download/attachments/91881669/ContextItem%20-%202462418.pdf?version=1&modificationDate=1469219805077&cacheVersion=1&api=v2) any non-zero value represents a change from a prior version.   A data modeler may include an attribute on the LoggedVariable to signal that version used.
3. Base Type.  I've extended the 3 types currently in the representation system with Flag (i.e., boolean / indicator).  I purposely omitted Date Time, which I would advocate can be represented as an ISO 8601 string or 64bit integer at the DTD may define.
4. Localizations.   I did not include a default name or description.   Rather, each DTD requires 1 or more Localizations which themselves contain the definitions.   Enumeration Items follow the same pattern, containing only a numeric code.
5. Presentations.  See #90
6. Geo Political Context.  See #91
7. Keywords.  Optional query terms defined by the authors of the DTD, relevant only to the published instance of the definitions.
8. IsRetired flag, allowing for deprecation within the published definitions list.
9. Per-Type Attributes
   a. Enumeration.   Each item has a numeric code and one or more localized names for the item.   Also, there is a default item code.
   b. Text.   An optional validation Regex.
   c. Numeric. 
       i. One of several strict types allowing for concise binary representations of the data.
       ii.  UOM Code.  Required.  Each item will carry a mandatory UOM.
       iii. Optional Minimum/Maximum/Default values universally applicable to the Data Type Definition.   These are separate from user-defined Min/Max/Defaults which are coded as a usage attribute on the variable instance.

**Comment by knelson-farmbeltnorth** [comment]
Initial discussion in 15 March 2023 meeting.  Feedback from the group:

- Should the DTD have a default localization?  No strong opinions. 
- Presentation indeed does not seem to belong in a data type registry.   It may make sense to include as a defined structure in which an individual data modeler can pass known presentations to his consumers.  I.e., within instances of the model vs. in the list of standard types
- The group could not think of an example necessitating the free text type of DTD.  Any variable definition would seem to require a defined list, a numeric value or true/false.  
- It may be useful to augment NumericAttributes with number of significant digits.

**Comment by knelson-farmbeltnorth** [comment]
Adding 3 examples for discussion:

![Example1](https://user-images.githubusercontent.com/31662976/225386913-3b9b6e0c-3739-433f-8022-52d482b59cf7.png)
![Example 2](https://user-images.githubusercontent.com/31662976/225386926-fb50f8f2-1ba3-49fc-868d-58cb56c111f4.png)
![Example 3](https://user-images.githubusercontent.com/31662976/225386945-74aa1599-e87c-49e2-8158-2fa3e844e72d.png)

**Comment by knelson-farmbeltnorth** [comment]
The above examples invite the question of whether the Keywords property should be moved to each individual Localiazation object.

**Comment by jim-wilson-kt** [comment]
I recommend changing the statement: "They may match one or more of the English localizations."

To this: "If one English localization is specified, they must match. If two or more English localizations is specified, they must match one of them with the same English localization used for all DTDs, and they may match other English localizations."

My reason for suggesting this is that it would be unclear to an implementer why a DTD name/description in English would differ from all English localizations of that name/description, which would be possible without the change I suggested.

**Comment by knelson-farmbeltnorth** [comment]
Uploading revised diagrams for discussion to include name/description and a basic implementation of DTD scope
![ADAPT Data Type Definition Model](https://user-images.githubusercontent.com/31662976/230094214-eb677116-105e-4b76-87d7-abb74f9bd5d8.png)

![Example1](https://user-images.githubusercontent.com/31662976/230094247-e853c760-1c02-431a-877f-4d1d2858eb2e.png)

![Example 2](https://user-images.githubusercontent.com/31662976/230094285-c2c96636-ce25-438d-b30d-da2b3dd6ce52.png)

![Example 3](https://user-images.githubusercontent.com/31662976/230094314-fe0c0b96-5e52-4fb3-8497-2e3e7098805f.png)

**Comment by knelson-farmbeltnorth** [comment]
Agreement in 5 April 2023 meeting that Scope should be a listing of ADAPT object names, not a textual description.   Preliminary agreement to remove Presentation from the model.

**Comment by knelson-farmbeltnorth** [comment]
Open questions: 
-Is it satisfactory to have a list of strings corresponding to ADAPT object names as the Scope?
-Do Keywords belong on the central object or on the Localization?
-When would we retire a DTD?

**Comment by knelson-farmbeltnorth** [comment]
Decided in 19 & 26 April 2023 meetings:
-Scope will be a list of enumerated values pointing to a single enumeration containing a list of ADAPT objects to which these data can be affixed.
-Keywords & IsRetired will be left as proposed above.
-We will continue to use "DataTypeDefinition."
