### ISSUE TITLE
PermittedProduct

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#9]
Logistics.PermittedProduct is an orphaned class of vague intention.   Who or what is permitting a product?   

Pending clarity I'm inclined to omit it going forward as an incomplete concept.

**Comment by strhea** [comment]
Thinking back to the original "data card" orientation of ADAPT, it was POSSIBLE for an ADM to contain data from multiple "growers". In that instance, you would need a way to distinguish which Product(s) should appear in a pick list for a given Grower.

**Comment by knelson-farmbeltnorth** [comment]
If that is the meaning, I think "AvailableProduct" would be a lot clearer and avoid confusion that this defines a pesticide that is "permitted" in certain circumstances. 

Also, as is it is orphaned without any ability to store it.   I would suggest we make it a List of values on the Grower (or perhaps future Organizational node) entity.

**Comment by knelson-farmbeltnorth** [comment]
25 August committee agreement to remove this entity.   It is a use case that has not materialized due to its lack of being wired up in ADAPT today.   At such time we need to map products to growers, we can re-examine and add to the model.
