### ISSUE TITLE
Simplifying Geo Political Contexts

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#91]
Child issue of #88 for discussion.

The Geo Political Context  object is substantially simplified vs. its current specification/implementation.

1. I'm requiring an ISO3166-alpha 2 code for the country. This allows not only specification of EU alongside its member countries, but is a standard in wide usage. The FAO system listed as default in the C# code is a dead link.

2.  Level 1 & 2 are free text entry, with optional URLs for context/validation. It is not reasonable to enforce any fixed enumeration on these levels where such may not exist.

3. I dropped the concepts of descriptions and language labels here. These are redundancies if they represent friendly names for the geopolitical entities. Users should reference from ISO3166 in their chosen language.

**Comment by knelson-farmbeltnorth** [comment]
In addition, I'm inclined toward modelling GeoPolitical Context by value rather than by reference to a common list of contexts in the Catalog.   These will primarily be used with Context Items where a centralized Catalog will not necessarily exist (in the canonical DTD listing), and the amount contexts will repeat seems insufficient to otherwise abstract into common instances.

**Comment by aferreyra** [comment]
We used 3166 and Geonames in other applications. Geonames has multiple admin levels; 3166 has two, you just need the right part.

Thanks,

Andres

**Comment by aferreyra** [comment]
Let's please be careful with what we do with ContextItem. That stuff is currently part of ASABE/ANSI US National Standard S632-1. Let's try to not divergen unnecessarily from something that was initially created to support ADAPT. If we DO have to diverge, the time is now, because we have a window of opportunity to get those changes into the ISO CD 7673-1, which is the international version of it.

**Comment by knelson-farmbeltnorth** [comment]
@strhea @aferreyra We discussed this at length in yesterday's meeting.   There was general agreement that my proposal of using 3166 exclusively will not work.    After researching this in more detail, I'm inclined to revert more closely to the GPC as currently defined.  However, there are a few things that still need discussion.

1. The FAO ontology as near as I can tell is defunct.   I can find no link to it that works, nor any published replacement.   I suggest we remove it from the list of acceptable vocabularies.

2.  I'm not sure I understand the value of GPCLevel, and our limitation to 2 levels.   While we may see limited likelihood of context specificity for, e.g., a US township, why limit our ability to model it? If we are using a controlled vocabulary, to the extent it is needed we should be able to determine its level from that vocabulary.      I'm inclined to remove that level concept.

3. Lastly, I still believe that adding localized labels for geopolitical entities is extraneous information for ADAPT.  These can also be referenced from the published sources.

Regarding alterations to ContextItem, some changes will be unavoidable as we work to harmonize it with the Representation system.   Perhaps we need to think of it as a version 2.

**Comment by knelson-farmbeltnorth** [comment]
@strhea and I had a follow-up meeting on this.   We agreed that we should use a single ontology within ADAPT and GeoNames seems to be the most comprehensive option.   

Looking at a Geonames entry for, e.g., California (https://sws.geonames.org/5332921), there is a hierarchy of codes that we could separate by a colon ("US:CA") to identify California by code and avoid any further Geo Political Context data in ADAPT.

However, within the formal Geonames ontology, the URI for California is "https://sws.geonames.org/5332921", and the US & CA codes do not appear in the formal ontology.

As such, my current recommendation would be to have a simple GeoPoltical Context class with 2 members to include both a formal URI for automated queries and a human-readable description.   We would include this by value where-ever we wished to reference a GeoPoliticalContext:
  
"GeoPoliticalContext":  {
      "GeoNamesURI": "https://sws.geonames.org/5332921",
      "Description": "California"
}

I could be convinced to dispense with the description and simply use the URI as a string property as a substitute for the entire object.

**Comment by crutt** [comment]
@knelson-farmbeltnorth No qualms here, using a single ontology is simple and clean.

Glancing through the documentation and export [readme](https://download.geonames.org/export/dump/readme.txt), it appears that the `geonameid` is the primary identifier that would be used with the geonames [dataset](https://download.geonames.org/export/dump) or [web service](https://www.geonames.org/export/web-services.html).

I would recommend adding the `GeoName` to the GeoPoliticalContext attributes.  I think there is still some limited benefit in including the `GeoNamesUri`, as it aids discoverability without additional documentation.

```
"GeoPoliticalContext": {
  "GeoNamesURI": "https://sws.geonames.org/5332921",
  "GeoNameId": "5332921",
  "Description": "California"
}
```

http://api.geonames.org/hierarchy?geonameId=5332921&username=adapt

**Comment by knelson-farmbeltnorth** [comment]
We agreed in the 10 May 2023 meeting to format it as follows:

"GeoPoliticalContext": {
  "ISO3166-2Code": "US-CA",
  "GeoNamesId": "5332921",
  "Description": "California"
}

ISO 3166-2 Code will be required, and GeoNamesId/Description will be optional in cases where a more granular geography is required than possible with 3166-2.
